export PATH="~/bin:/usr/local/bin:$PATH:`yarn global bin`"

# bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# bash powerline
source ~/.bash-powerline

# git completion
export GIT_PS1_SHOWDIRTYSTATE=1
source ~/.gitcompletion

# nvm
export NVM_DIR="$HOME/.nvm"
source "/usr/local/opt/nvm/nvm.sh"

# pyenv
PYENV_ROOT=/usr/local/var/pyenv
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then 
    eval "$(pyenv virtualenv-init -)"
fi

# term
export CLICOLOR=1
export EDITOR="code"
export TERM="xterm-256color"

# colored ls output
alias ls="ls -G"
